namespace MALClient.Models.Enums
{
    public enum AnimeGenreSearch
    {
        Action = 1,
        Adventure = 2,
        Cars = 3,
        Comedy = 4,
        AvanteGarde = 5,
        Demons = 6,
        Mystery = 7,
        Drama = 8,
        Ecchi = 9,
        Fantasy = 10,
        Game = 11,
        Hentai = 12,
        Historical = 13,
        Horror = 14,
        Kids = 15,
        Magic = 16,
        MartialArts = 17,
        Mecha = 18,
        Music = 19,
        Parody = 20,
        Samurai = 21,
        Romance = 22,
        School = 23,
        SciFi = 24,
        Shoujo = 25,
        GirlsLove = 26,
        Shounen = 27,
        BoysLove = 28,
        Space = 29,
        Sports = 30,
        SuperPower = 31,
        Vampire = 32,
        Harem = 35,
        SliceOfLife = 36,
        Supernatural = 37,
        Military = 38,
        Police = 39,
        Psychological = 40,
        Suspense = 41,
        Seinen = 42,
        Josei = 43,
        AwardWinning = 46,
        Gourmet = 47,
        WorkLife = 48,
        Erotica = 49
    }
}
