<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>MALPlus.Core</AssemblyName>
    <RootNamespace>MALPlus.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.28" />
    <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="XShared\**\*.cs"
             Exclude="XShared\bin\**;XShared\obj\**;XShared\Properties\**;XShared\Utils\PreserveAtribute.cs"
             Link="XShared\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="Models\**\*.cs"
             Exclude="Models\bin\**;Models\obj\**;Models\Properties\**;Models\Interfaces\IAnimeLibraryDataStorage.cs"
             Link="Models\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="BBCode\**\*.cs"
             Exclude="BBCode\bin\**;BBCode\obj\**;BBCode\Properties\**"
             Link="BBCode\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="Adapters\**\*.cs"
             Exclude="Adapters\bin\**;Adapters\obj\**;Adapters\Properties\**"
             Link="Adapters\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
