using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using MALClient.Android.Resources;

namespace MALClient.Android.Fragments.SettingsFragments
{
    public partial class SettingsGeneralFragment
    {
        #region Views

        private RadioButton _settingsPageGeneralRadioAnimeList;
        private RadioButton _settingsPageGeneralRadioMangaList;
        private RadioButton _settingsPageGeneralRadioDiscover;
        private RadioGroup _settingsPageGeneralStartPageRadioGroup;
        private RadioButton _settingsPageGeneralRadioDarkTheme;
        private RadioButton _settingsPageGeneralRadioLightTheme;
        private RadioGroup _settingsPageGeneralThemeRadioGroup;
        private ImageButton _settingsPageGeneralColorOrange;
        private ImageButton _settingsPageGeneralColorPurple;
        private ImageButton _settingsPageGeneralColorBlue;
        private ImageButton _settingsPageGeneralColorLime;
        private ImageButton _settingsPageGeneralColorPink;
        private ImageButton _settingsPageGeneralColorCyan;
        private ImageButton _settingsPageGeneralColorSkyBlue;
        private ImageButton _settingsPageGeneralColorRed;
        private Switch _settingsPageGeneralAmoledSwitch;
        private Button _settingsPageGeneralThemeChangeApply;
        private Switch _settingsPageGeneralEnableSwipeSwitch;
        private Switch _settingsPageGeneralPullHigherSwitch;
        private Switch _settingsPageGeneralSeasonSwitch;
        private Switch _settingsPageGeneralAutoSortSwitch;
        private Switch _settingsPageGeneralVolsImportantSwitch;
        private Switch _settingsPageGeneralHideHamburgerMangaSwitch;
        private Switch _settingsPageGeneralPreferEnglishTitleSwitch;
        private Switch _settingsPageGeneralSmallerGridItems;
        private Switch _settingsPageGeneralReverseSwipeOrder;
        private Switch _settingsPageGeneralDisplayScoreDialog;
        private Switch _settingsPageGeneralEnableShareButton;
        private Switch _settingsPageGeneralEnableDisplayUnsetScores;
        private Switch _settingsPageGeneralHideDecrementButtons;
        private Switch _settingsPageGeneralHideGlobalScore;
        private Switch _settingsPageGeneralSqueezeOneMoreItem;
        private Switch _settingsPageGeneralDontAskMoveOnHold;
        private Switch _settingsPageGeneralShowPriorities;
        private Switch _settingsPageGeneralDontShowLowPriorities;
        private RadioButton _settingsPageGeneralAnimeSortTitleRadioBtn;
        private RadioButton _settingsPageGeneralAnimeScoreTitleRadioBtn;
        private RadioButton _settingsPageGeneralAnimeWatchedTitleRadioBtn;
        private RadioButton _settingsPageGeneralAnimeSoonAiringTitleRadioBtn;
        private RadioButton _settingsPageGeneralAnimeLastWatchTitleRadioBtn;
        private RadioButton _settingsPageGeneralAnimeSortNoneRadioBtn;
        private RadioGroup _settingsPageGeneralAnimeSortRadioGroup;
        private Switch _settingsPageGeneralAnimeSortDescendingSwitch;
        private RadioButton _settingsPageGeneralMangaSortTitleRadioBtn;
        private RadioButton _settingsPageGeneralMangaSortScoreRadioBtn;
        private RadioButton _settingsPageGeneralMangaSortReadRadioBtn;
        private RadioButton _settingsPageGeneralMangaLastReadTitleRadioBtn;
        private RadioButton _settingsPageGeneralMangaSortNoneRadioBtn;
        private RadioGroup _settingsPageGeneralMangaSortRadioGroup;
        private Switch _settingsPageGeneralMangaSortDescendingSwitch;
        private Spinner _settingsPageGeneralWatchingViewModeSpinner;
        private Spinner _settingsPageGeneralCompletedViewModeSpinner;
        private Spinner _settingsPageGeneralOnHoldViewModeSpinner;
        private Spinner _settingsPageGeneralDroppedViewModeSpinner;
        private Spinner _settingsPageGeneralPtwViewModeSpinner;
        private Spinner _settingsPageGeneralAllViewModeSpinner;
        private Spinner _settingsPageGeneralAnimeFilterSpinner;
        private Spinner _settingsPageGeneralMangaFilerSpinner;
        private Spinner _settingsPageGeneralDefaultAddedStatusSpinner;
        private Switch _settingsPageGeneralStartDateWhenAddCheckBox;
        private Switch _settingsPageGeneralStartDateWhenWatchCheckBox;
        private Switch _settingsPageGeneralEndDateWhenCompleted;
        private Switch _settingsPageGeneralEndDateWhenDropCheckBox;
        private Switch _settingsPageGeneralAllowDateOverrideCheckBox;
        private TextView _settingsPageGeneralAirDayOffsetTextView;
        private SeekBar _settingsPageGeneralAirDayOffsetSlider;
        private TextView _settingsPageGeneralAiringNotificationOffsetTextView;
        private SeekBar _settingsPageGeneralAiringNotificationOffsetSlider;

        public RadioButton SettingsPageGeneralRadioAnimeList => GetView(ref _settingsPageGeneralRadioAnimeList, Resource.Id.SettingsPageGeneralRadioAnimeList);
        public RadioButton SettingsPageGeneralRadioMangaList => GetView(ref _settingsPageGeneralRadioMangaList, Resource.Id.SettingsPageGeneralRadioMangaList);
        public RadioButton SettingsPageGeneralRadioDiscover => GetView(ref _settingsPageGeneralRadioDiscover, Resource.Id.SettingsPageGeneralRadioDiscover);
        public RadioGroup SettingsPageGeneralStartPageRadioGroup => GetView(ref _settingsPageGeneralStartPageRadioGroup, Resource.Id.SettingsPageGeneralStartPageRadioGroup);
        public RadioButton SettingsPageGeneralRadioDarkTheme => GetView(ref _settingsPageGeneralRadioDarkTheme, Resource.Id.SettingsPageGeneralRadioDarkTheme);
        public RadioButton SettingsPageGeneralRadioLightTheme => GetView(ref _settingsPageGeneralRadioLightTheme, Resource.Id.SettingsPageGeneralRadioLightTheme);
        public RadioGroup SettingsPageGeneralThemeRadioGroup => GetView(ref _settingsPageGeneralThemeRadioGroup, Resource.Id.SettingsPageGeneralThemeRadioGroup);
        public ImageButton SettingsPageGeneralColorOrange => GetView(ref _settingsPageGeneralColorOrange, Resource.Id.SettingsPageGeneralColorOrange);
        public ImageButton SettingsPageGeneralColorPurple => GetView(ref _settingsPageGeneralColorPurple, Resource.Id.SettingsPageGeneralColorPurple);
        public ImageButton SettingsPageGeneralColorBlue => GetView(ref _settingsPageGeneralColorBlue, Resource.Id.SettingsPageGeneralColorBlue);
        public ImageButton SettingsPageGeneralColorLime => GetView(ref _settingsPageGeneralColorLime, Resource.Id.SettingsPageGeneralColorLime);
        public ImageButton SettingsPageGeneralColorPink => GetView(ref _settingsPageGeneralColorPink, Resource.Id.SettingsPageGeneralColorPink);
        public ImageButton SettingsPageGeneralColorCyan => GetView(ref _settingsPageGeneralColorCyan, Resource.Id.SettingsPageGeneralColorCyan);
        public ImageButton SettingsPageGeneralColorSkyBlue => GetView(ref _settingsPageGeneralColorSkyBlue, Resource.Id.SettingsPageGeneralColorSkyBlue);
        public ImageButton SettingsPageGeneralColorRed => GetView(ref _settingsPageGeneralColorRed, Resource.Id.SettingsPageGeneralColorRed);
        public Switch SettingsPageGeneralAmoledSwitch => GetView(ref _settingsPageGeneralAmoledSwitch, Resource.Id.SettingsPageGeneralAmoledSwitch);
        public Button SettingsPageGeneralThemeChangeApply => GetView(ref _settingsPageGeneralThemeChangeApply, Resource.Id.SettingsPageGeneralThemeChangeApply);
        public Switch SettingsPageGeneralEnableSwipeSwitch => GetView(ref _settingsPageGeneralEnableSwipeSwitch, Resource.Id.SettingsPageGeneralEnableSwipeSwitch);
        public Switch SettingsPageGeneralPullHigherSwitch => GetView(ref _settingsPageGeneralPullHigherSwitch, Resource.Id.SettingsPageGeneralPullHigherSwitch);
        public Switch SettingsPageGeneralSeasonSwitch => GetView(ref _settingsPageGeneralSeasonSwitch, Resource.Id.SettingsPageGeneralSeasonSwitch);
        public Switch SettingsPageGeneralAutoSortSwitch => GetView(ref _settingsPageGeneralAutoSortSwitch, Resource.Id.SettingsPageGeneralAutoSortSwitch);
        public Switch SettingsPageGeneralVolsImportantSwitch => GetView(ref _settingsPageGeneralVolsImportantSwitch, Resource.Id.SettingsPageGeneralVolsImportantSwitch);
        public Switch SettingsPageGeneralHideHamburgerMangaSwitch => GetView(ref _settingsPageGeneralHideHamburgerMangaSwitch, Resource.Id.SettingsPageGeneralHideHamburgerMangaSwitch);
        public Switch SettingsPageGeneralPreferEnglishTitleSwitch => GetView(ref _settingsPageGeneralPreferEnglishTitleSwitch, Resource.Id.SettingsPageGeneralPreferEnglishTitleSwitch);
        public Switch SettingsPageGeneralSmallerGridItems => GetView(ref _settingsPageGeneralSmallerGridItems, Resource.Id.SettingsPageGeneralSmallerGridItems);
        public Switch SettingsPageGeneralReverseSwipeOrder => GetView(ref _settingsPageGeneralReverseSwipeOrder, Resource.Id.SettingsPageGeneralReverseSwipeOrder);
        public Switch SettingsPageGeneralDisplayScoreDialog => GetView(ref _settingsPageGeneralDisplayScoreDialog, Resource.Id.SettingsPageGeneralDisplayScoreDialog);
        public Switch SettingsPageGeneralEnableShareButton => GetView(ref _settingsPageGeneralEnableShareButton, Resource.Id.SettingsPageGeneralEnableShareButton);
        public Switch SettingsPageGeneralEnableDisplayUnsetScores => GetView(ref _settingsPageGeneralEnableDisplayUnsetScores, Resource.Id.SettingsPageGeneralEnableDisplayUnsetScores);
        public Switch SettingsPageGeneralHideDecrementButtons => GetView(ref _settingsPageGeneralHideDecrementButtons, Resource.Id.SettingsPageGeneralHideDecrementButtons);
        public Switch SettingsPageGeneralHideGlobalScore => GetView(ref _settingsPageGeneralHideGlobalScore, Resource.Id.SettingsPageGeneralHideGlobalScore);
        public Switch SettingsPageGeneralSqueezeOneMoreItem => GetView(ref _settingsPageGeneralSqueezeOneMoreItem, Resource.Id.SettingsPageGeneralSqueezeOneMoreItem);
        public Switch SettingsPageGeneralDontAskMoveOnHold => GetView(ref _settingsPageGeneralDontAskMoveOnHold, Resource.Id.SettingsPageGeneralDontAskMoveOnHold);
        public Switch SettingsPageGeneralShowPriorities => GetView(ref _settingsPageGeneralShowPriorities, Resource.Id.SettingsPageGeneralShowPriorities);
        public Switch SettingsPageGeneralDontShowLowPriorities => GetView(ref _settingsPageGeneralDontShowLowPriorities, Resource.Id.SettingsPageGeneralDontShowLowPriorities);
        public RadioButton SettingsPageGeneralAnimeSortTitleRadioBtn => GetView(ref _settingsPageGeneralAnimeSortTitleRadioBtn, Resource.Id.SettingsPageGeneralAnimeSortTitleRadioBtn);
        public RadioButton SettingsPageGeneralAnimeScoreTitleRadioBtn => GetView(ref _settingsPageGeneralAnimeScoreTitleRadioBtn, Resource.Id.SettingsPageGeneralAnimeScoreTitleRadioBtn);
        public RadioButton SettingsPageGeneralAnimeWatchedTitleRadioBtn => GetView(ref _settingsPageGeneralAnimeWatchedTitleRadioBtn, Resource.Id.SettingsPageGeneralAnimeWatchedTitleRadioBtn);
        public RadioButton SettingsPageGeneralAnimeSoonAiringTitleRadioBtn => GetView(ref _settingsPageGeneralAnimeSoonAiringTitleRadioBtn, Resource.Id.SettingsPageGeneralAnimeSoonAiringTitleRadioBtn);
        public RadioButton SettingsPageGeneralAnimeLastWatchTitleRadioBtn => GetView(ref _settingsPageGeneralAnimeLastWatchTitleRadioBtn, Resource.Id.SettingsPageGeneralAnimeLastWatchTitleRadioBtn);
        public RadioButton SettingsPageGeneralAnimeSortNoneRadioBtn => GetView(ref _settingsPageGeneralAnimeSortNoneRadioBtn, Resource.Id.SettingsPageGeneralAnimeSortNoneRadioBtn);
        public RadioGroup SettingsPageGeneralAnimeSortRadioGroup => GetView(ref _settingsPageGeneralAnimeSortRadioGroup, Resource.Id.SettingsPageGeneralAnimeSortRadioGroup);
        public Switch SettingsPageGeneralAnimeSortDescendingSwitch => GetView(ref _settingsPageGeneralAnimeSortDescendingSwitch, Resource.Id.SettingsPageGeneralAnimeSortDescendingSwitch);
        public RadioButton SettingsPageGeneralMangaSortTitleRadioBtn => GetView(ref _settingsPageGeneralMangaSortTitleRadioBtn, Resource.Id.SettingsPageGeneralMangaSortTitleRadioBtn);
        public RadioButton SettingsPageGeneralMangaSortScoreRadioBtn => GetView(ref _settingsPageGeneralMangaSortScoreRadioBtn, Resource.Id.SettingsPageGeneralMangaSortScoreRadioBtn);
        public RadioButton SettingsPageGeneralMangaSortReadRadioBtn => GetView(ref _settingsPageGeneralMangaSortReadRadioBtn, Resource.Id.SettingsPageGeneralMangaSortReadRadioBtn);
        public RadioButton SettingsPageGeneralMangaLastReadTitleRadioBtn => GetView(ref _settingsPageGeneralMangaLastReadTitleRadioBtn, Resource.Id.SettingsPageGeneralMangaLastReadTitleRadioBtn);
        public RadioButton SettingsPageGeneralMangaSortNoneRadioBtn => GetView(ref _settingsPageGeneralMangaSortNoneRadioBtn, Resource.Id.SettingsPageGeneralMangaSortNoneRadioBtn);
        public RadioGroup SettingsPageGeneralMangaSortRadioGroup => GetView(ref _settingsPageGeneralMangaSortRadioGroup, Resource.Id.SettingsPageGeneralMangaSortRadioGroup);
        public Switch SettingsPageGeneralMangaSortDescendingSwitch => GetView(ref _settingsPageGeneralMangaSortDescendingSwitch, Resource.Id.SettingsPageGeneralMangaSortDescendingSwitch);
        public Spinner SettingsPageGeneralWatchingViewModeSpinner => GetView(ref _settingsPageGeneralWatchingViewModeSpinner, Resource.Id.SettingsPageGeneralWatchingViewModeSpinner);
        public Spinner SettingsPageGeneralCompletedViewModeSpinner => GetView(ref _settingsPageGeneralCompletedViewModeSpinner, Resource.Id.SettingsPageGeneralCompletedViewModeSpinner);
        public Spinner SettingsPageGeneralOnHoldViewModeSpinner => GetView(ref _settingsPageGeneralOnHoldViewModeSpinner, Resource.Id.SettingsPageGeneralOnHoldViewModeSpinner);
        public Spinner SettingsPageGeneralDroppedViewModeSpinner => GetView(ref _settingsPageGeneralDroppedViewModeSpinner, Resource.Id.SettingsPageGeneralDroppedViewModeSpinner);
        public Spinner SettingsPageGeneralPtwViewModeSpinner => GetView(ref _settingsPageGeneralPtwViewModeSpinner, Resource.Id.SettingsPageGeneralPtwViewModeSpinner);
        public Spinner SettingsPageGeneralAllViewModeSpinner => GetView(ref _settingsPageGeneralAllViewModeSpinner, Resource.Id.SettingsPageGeneralAllViewModeSpinner);
        public Spinner SettingsPageGeneralAnimeFilterSpinner => GetView(ref _settingsPageGeneralAnimeFilterSpinner, Resource.Id.SettingsPageGeneralAnimeFilterSpinner);
        public Spinner SettingsPageGeneralMangaFilerSpinner => GetView(ref _settingsPageGeneralMangaFilerSpinner, Resource.Id.SettingsPageGeneralMangaFilerSpinner);
        public Spinner SettingsPageGeneralDefaultAddedStatusSpinner => GetView(ref _settingsPageGeneralDefaultAddedStatusSpinner, Resource.Id.SettingsPageGeneralDefaultAddedStatusSpinner);
        public Switch SettingsPageGeneralStartDateWhenAddCheckBox => GetView(ref _settingsPageGeneralStartDateWhenAddCheckBox, Resource.Id.SettingsPageGeneralStartDateWhenAddCheckBox);
        public Switch SettingsPageGeneralStartDateWhenWatchCheckBox => GetView(ref _settingsPageGeneralStartDateWhenWatchCheckBox, Resource.Id.SettingsPageGeneralStartDateWhenWatchCheckBox);
        public Switch SettingsPageGeneralEndDateWhenCompleted => GetView(ref _settingsPageGeneralEndDateWhenCompleted, Resource.Id.SettingsPageGeneralEndDateWhenCompleted);
        public Switch SettingsPageGeneralEndDateWhenDropCheckBox => GetView(ref _settingsPageGeneralEndDateWhenDropCheckBox, Resource.Id.SettingsPageGeneralEndDateWhenDropCheckBox);
        public Switch SettingsPageGeneralAllowDateOverrideCheckBox => GetView(ref _settingsPageGeneralAllowDateOverrideCheckBox, Resource.Id.SettingsPageGeneralAllowDateOverrideCheckBox);
        public TextView SettingsPageGeneralAirDayOffsetTextView => GetView(ref _settingsPageGeneralAirDayOffsetTextView, Resource.Id.SettingsPageGeneralAirDayOffsetTextView);
        public SeekBar SettingsPageGeneralAirDayOffsetSlider => GetView(ref _settingsPageGeneralAirDayOffsetSlider, Resource.Id.SettingsPageGeneralAirDayOffsetSlider);
        public TextView SettingsPageGeneralAiringNotificationOffsetTextView => GetView(ref _settingsPageGeneralAiringNotificationOffsetTextView, Resource.Id.SettingsPageGeneralAiringNotificationOffsetTextView);
        public SeekBar SettingsPageGeneralAiringNotificationOffsetSlider => GetView(ref _settingsPageGeneralAiringNotificationOffsetSlider, Resource.Id.SettingsPageGeneralAiringNotificationOffsetSlider);

        #endregion
    }
}
